# Generated by Django 3.2.21 on 2023-09-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('BG', 'black/grey'), ('GR', 'green'), ('WH', 'white'), ('BL', 'blue'), ('BR', 'braun'), ('RO', 'red/orange'), ('YE', 'yellow'), ('O', 'Other')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('AX', 'Axess'), ('CI', 'Ciclista'), ('CU', 'Cube'), ('KT', 'KTM'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
