# Generated by Django 3.2.21 on 2023-09-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230912_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='brand',
        ),
    ]
